[package]
name = "ciro_contracts"
version = "0.1.0"
edition = "2024_07"
description = "CIRO Network smart contracts for Starknet"
repository = "https://github.com/Ciro-AI-Labs/ciro-network"
license = "MIT"
authors = ["CIRO Labs <contact@ciro.ai>"]
keywords = ["starknet", "cairo", "smart-contracts", "depin"]

[dependencies]
starknet = "2.12.0"
# Updated OpenZeppelin to latest version 0.20.0 for better Cairo 2.12.0+ compatibility
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.20.0" }

[dev-dependencies]
# Updated snforge_std to meet the recommended version requirement ^0.47.0
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.47.0" }

[[target.starknet-contract]]
casm = true

[tool.snforge]
# Exit first on any failed test  
exit_first = true
# Use the Cairo 2.12.0 compatible fork URL
fork = [
    { name = "Mainnet", url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7", block_id.number = "0" }
]

[scripts]
build = "scarb build"
test = "snforge test"
format = "scarb fmt"
check = "scarb check"

# Cairo 2.12.0 Advanced Optimization Features
[tool.cairo]
# Enable compilation caching for faster rebuilds
cache_enabled = true
# Enable aggressive code deduplication optimization
optimize_code_size = true
# Enable gas optimization features
optimize_gas = true
# Advanced deduplication settings
deduplicate_functions = true
inline_small_functions = true
# Sierra-level optimizations
optimize_sierra = true
# Enable loop optimizations
optimize_loops = true 