[book]
title = "CIRO Network Documentation"
description = "Complete documentation for the CIRO Network decentralized compute layer"
authors = ["CIRO Labs Team"]
language = "en"
multilingual = false
src = "src"
build-dir = "book"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[preprocessor]

[preprocessor.links]
# Process internal links automatically

[preprocessor.index]
# Generate index pages automatically

# [preprocessor.last-changed]
# Show last changed information (enable after first git commit)
# command = "mdbook-last-changed"
# renderer = ["html"]

[preprocessor.mermaid]

# Disable KaTeX temporarily to fix syntax errors
# [preprocessor.katex]
# # KaTeX math rendering for better equation display
# # Only process content inside explicit math delimiters
# macros = ""
# output-dir = "katex"
# create-css = true
# no-css = false
# include-src = false

[output]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
site-url = "/"
cname = "docs.ciro.network"
git-repository-url = "https://github.com/ciro-network/ciro-network"
edit-url-template = "https://github.com/ciro-network/ciro-network/edit/main/docs/{path}"
additional-css = [
    "theme/ciro-theme.css",
    "theme/custom.css"
]
additional-js = [
    "theme/math-config.js",
    "theme/ciro-theme.js"
]
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = false
runnable = true 